import { MessageSquare, TerminalSquare } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { lessonById, studyLessons, type StudyLesson } from '../data/studyLessons'
import { Button, SecondaryButton, SuccessNotice } from '../components/ui'
import { useProgressStore, type Confidence } from '../store/progressStore'

type Mode = 'quick' | 'oral' | 'troubleshooting' | 'output'
const modes: { id: Mode; label: string; description: string }[] = [
  { id: 'quick', label: 'Быстрые вопросы', description: 'Короткие вопросы без длинной подготовки.' },
  { id: 'oral', label: 'Устное интервью', description: 'Ответь своими словами и честно сверься с чек-листом.' },
  { id: 'troubleshooting', label: 'Troubleshooting-интервью', description: 'Выбери следующую проверку и объясни гипотезу.' },
  { id: 'output', label: 'Разбор вывода', description: 'Найди важную строку и назови следующий шаг.' },
]

export function InterviewPage() {
  const [params] = useSearchParams(); const requested = params.get('lesson')
  const [lessonId, setLessonId] = useState<StudyLesson['id']>(() => lessonById.has(requested as StudyLesson['id']) ? requested as StudyLesson['id'] : 'linux-processes')
  const [mode, setMode] = useState<Mode>('quick'); const lesson = lessonById.get(lessonId)!
  return <div className="mx-auto max-w-5xl"><header className="border-b border-[#263035] pb-7"><p className="font-mono text-xs uppercase tracking-wide text-lime-300">Без AI · честная самооценка по структуре ответа</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">Собеседование</h1><p className="mt-3 max-w-3xl text-base leading-7 text-slate-400">Тренируй не только правильный факт, но и ход мысли: что уточнить, что проверить и как спокойно объяснить решение.</p></header>
    <div className="mt-6 flex flex-wrap gap-2" aria-label="Тема собеседования">{studyLessons.map((item) => <button key={item.id} onClick={() => setLessonId(item.id)} className={`rounded-md border px-3 py-2 text-sm ${lessonId === item.id ? 'border-lime-300 bg-lime-300/10 text-lime-200' : 'border-[#394348] text-slate-300 hover:border-[#566369]'}`}>{item.title.replace('Linux: ', '').replace('Kubernetes: ', '')}</button>)}</div>
    <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{modes.map((item) => <button key={item.id} onClick={() => setMode(item.id)} className={`rounded-lg border p-4 text-left ${mode === item.id ? 'border-lime-300/70 bg-lime-300/10' : 'border-[#2d383d] bg-[#171d20] hover:border-[#566369]'}`}><p className={mode === item.id ? 'font-semibold text-lime-200' : 'font-semibold text-white'}>{item.label}</p><p className="mt-2 text-xs leading-5 text-slate-400">{item.description}</p></button>)}</div>
    <div className="mt-7">{mode === 'quick' && <QuickRound lesson={lesson} />}{mode === 'oral' && <OralInterview lesson={lesson} />}{mode === 'troubleshooting' && <TroubleshootingInterview lesson={lesson} />}{mode === 'output' && <OutputReading lesson={lesson} />}</div>
  </div>
}

function QuickRound({ lesson }: { lesson: StudyLesson }) {
  const items = [
    ...lesson.interview,
    ...studyLessons.filter((candidate) => candidate.id !== lesson.id).flatMap((candidate) => candidate.interview),
  ].slice(0, 10)
  const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const item = items[index]
  return <section className="rounded-lg border border-[#2d383d] bg-[#171d20] p-6"><p className="font-mono text-xs uppercase tracking-wide text-lime-300">Быстрый вопрос {index + 1}/{items.length}</p><h2 className="mt-4 text-xl font-semibold leading-8 text-white">{item.question}</h2><p className="mt-3 text-sm leading-6 text-slate-400">Ответь вслух за 30–90 секунд, затем сверяйся со структурой.</p><div className="mt-6 flex flex-wrap gap-3"><Button onClick={() => setRevealed(true)}>Показать структуру</Button><SecondaryButton onClick={() => { setIndex((value) => (value + 1) % items.length); setRevealed(false) }}>Следующий</SecondaryButton></div>{revealed && <KeyPoints item={item} />}</section>
}

function OralInterview({ lesson }: { lesson: StudyLesson }) {
  const [index, setIndex] = useState(0); const [text, setText] = useState(''); const [revealed, setRevealed] = useState(false); const [saved, setSaved] = useState(false); const record = useProgressStore((state) => state.recordInterviewConfidence); const item = lesson.interview[index % lesson.interview.length]
  const grade = (confidence: Confidence) => { record(item.id, confidence); setSaved(true) }
  return <section className="rounded-lg border border-[#2d383d] bg-[#171d20] p-6"><div className="flex items-center gap-3"><MessageSquare className="text-lime-300" size={20} /><p className="font-mono text-xs uppercase tracking-wide text-lime-300">Связанный вопрос {index + 1}/{lesson.interview.length}</p></div><h2 className="mt-4 text-xl font-semibold leading-8 text-white">{item.question}</h2><textarea value={text} onChange={(event) => { setText(event.target.value); setSaved(false) }} placeholder="Сформулируй ответ как на интервью: коротко, структурно, своими словами." className="mt-5 min-h-36 w-full rounded-md border border-[#465158] bg-[#0a0e10] p-4 text-sm leading-6 text-slate-100 outline-none placeholder:text-slate-600 focus:border-lime-300" /><div className="mt-4 flex flex-wrap gap-3"><Button disabled={text.trim().length < 12} onClick={() => setRevealed(true)}>Сверить со структурой</Button><SecondaryButton onClick={() => { setIndex((value) => (value + 1) % lesson.interview.length); setText(''); setRevealed(false); setSaved(false) }}>Следующий вопрос</SecondaryButton></div>{revealed && <><KeyPoints item={item} /><div className="mt-4 rounded-md border border-[#394348] bg-[#151b1e] p-4"><p className="text-sm font-medium text-white">Как ты объяснил?</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => grade('missed')} className="rounded-md border border-red-300/60 px-3 py-2 text-sm text-red-100">Не упомянул</button><button onClick={() => grade('partial')} className="rounded-md border border-amber-300/60 px-3 py-2 text-sm text-amber-100">Частично</button><button onClick={() => grade('confident')} className="rounded-md border border-lime-300/60 px-3 py-2 text-sm text-lime-100">Уверенно</button></div>{saved && <p className="mt-3 text-sm text-lime-200">Оценка сохранена: слабые пункты попадут в повторение.</p>}</div></>}</section>
}

function TroubleshootingInterview({ lesson }: { lesson: StudyLesson }) {
  const steps = useMemo(() => lesson.guided.slice(0, 2), [lesson]); const [index, setIndex] = useState(0); const [selected, setSelected] = useState<number | undefined>(); const [hypothesis, setHypothesis] = useState(''); const item = steps[index]; const correct = selected === item.correct
  return <section className="rounded-lg border border-[#2d383d] bg-[#171d20] p-6"><div className="flex items-center gap-3"><TerminalSquare className="text-lime-300" size={20} /><p className="font-mono text-xs uppercase tracking-wide text-lime-300">Ситуация</p></div><h2 className="mt-4 text-xl font-semibold text-white">{lesson.situation}</h2><p className="mt-3 text-sm leading-6 text-slate-400">Выбери следующую проверку. Затем сформулируй гипотезу — приложение не делает вид, что понимает произвольный текст, а даёт честный эталон пути.</p><div className="mt-5"><p className="font-medium text-slate-100">{item.question}</p><div className="mt-3 grid gap-2">{item.options.map((option, optionIndex) => <button key={option} disabled={selected !== undefined} onClick={() => setSelected(optionIndex)} className={`rounded-md border p-3 text-left text-sm ${selected === optionIndex ? optionIndex === item.correct ? 'border-lime-300 bg-lime-300/10 text-lime-100' : 'border-red-300/70 bg-red-300/10 text-red-100' : 'border-[#394348] text-slate-300 hover:border-[#566369]'}`}>{option}</button>)}</div></div>{selected !== undefined && <div className="mt-5"><textarea value={hypothesis} onChange={(event) => setHypothesis(event.target.value)} placeholder="Гипотеза: что я ожидаю увидеть и почему эта команда уместна…" className="min-h-24 w-full rounded-md border border-[#465158] bg-[#0a0e10] p-3 text-sm text-slate-100 outline-none focus:border-lime-300" />{correct ? <SuccessNotice><div><p className="font-semibold">Логика верная.</p><p className="mt-1 leading-6 text-slate-200">Ожидаемый вывод: {item.output}. {item.explanation}</p></div></SuccessNotice> : <p className="mt-3 rounded-md border border-red-300/30 bg-red-300/10 p-3 text-sm text-red-100">Этот шаг сейчас не проверяет главную гипотезу. Вернись к симптомам.</p>}{correct && <div className="mt-4">{index < steps.length - 1 ? <Button onClick={() => { setIndex((value) => value + 1); setSelected(undefined); setHypothesis('') }}>Продолжить интервью</Button> : <Link to={lesson.challenge.route} className="inline-flex min-h-10 items-center gap-2 rounded-md border border-lime-300 bg-lime-300 px-4 text-sm font-semibold text-[#111711]">Открыть терминал и решить самостоятельно</Link>}</div>}</div>}</section>
}

function OutputReading({ lesson }: { lesson: StudyLesson }) {
  const [choice, setChoice] = useState<number | undefined>(); const [next, setNext] = useState(''); const correct = choice === 0
  return <section className="rounded-lg border border-[#2d383d] bg-[#171d20] p-6"><p className="font-mono text-xs uppercase tracking-wide text-lime-300">Прочитай вывод</p><pre className="mt-4 overflow-x-auto rounded-md border border-[#394348] bg-[#0a0e10] p-4 font-mono text-sm leading-6 text-slate-200">student@trainer:~$ {lesson.terminal.command}{'\n'}{lesson.terminal.output}</pre><p className="mt-5 font-medium text-white">Что здесь самое важное?</p><div className="mt-3 grid gap-2"><button onClick={() => setChoice(0)} className={`rounded-md border p-3 text-left text-sm ${choice === 0 ? 'border-lime-300 bg-lime-300/10 text-lime-100' : 'border-[#394348] text-slate-300'}`}>{lesson.terminal.focus}</button><button onClick={() => setChoice(1)} className={`rounded-md border p-3 text-left text-sm ${choice === 1 ? 'border-red-300/70 bg-red-300/10 text-red-100' : 'border-[#394348] text-slate-300'}`}>Любая строка с числом — это уже готовая причина.</button></div>{choice !== undefined && <div className="mt-4"><textarea value={next} onChange={(event) => setNext(event.target.value)} placeholder="Какую команду выполнишь дальше и что она проверит?" className="min-h-24 w-full rounded-md border border-[#465158] bg-[#0a0e10] p-3 text-sm text-slate-100 outline-none focus:border-lime-300" />{correct && <p className="mt-3 text-sm leading-6 text-lime-200">Верно. Эталон следующего шага: {lesson.guided[0].commandQuestion}</p>}</div>}</section>
}

function KeyPoints({ item }: { item: StudyLesson['interview'][number] }) { return <SuccessNotice><div><p className="font-semibold">Эталонная структура ответа</p><ul className="mt-2 space-y-1 leading-6 text-slate-200">{item.keyPoints.map((point) => <li key={point}>• {point}</li>)}</ul></div></SuccessNotice> }
